"""
Point Comparison Utilities - Reusable tools for comparing plot data points.

This module provides generic utilities for extracting data points from debug logs
and comparing them between monolith and modular implementations. It is designed
to be parameter-agnostic and work for any monolith-to-modular conversion.

The MAIN EVENT of debugging is the point-to-point coordinate comparison.
A successful conversion must show 100% match on all coordinates.

Usage:
    from geotechnical_plotting.debug_utils.point_comparison import (
        extract_points_from_log,
        compare_point_lists,
        generate_comparison_report,
        run_full_comparison,
    )

    # Extract points from both log files
    modular_points = extract_points_from_log("logs/modular.log", pattern="MODULAR")
    monolith_points = extract_points_from_log("logs/monolith.log", pattern="MONOLITH")

    # Compare and get report
    report = compare_point_lists(monolith_points, modular_points)
    print_comparison_report(report)
"""

import re
import logging
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any, NamedTuple
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════
# 📊 DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class DataPoint:
    """
    Represents a single data point extracted from a log file.

    Attributes:
        location_id: Location identifier (e.g., 'BH1', 'TP01')
        depth: Depth value
        x_value: X coordinate value
        y_value: Y coordinate value
        investigation: Investigation name (optional)
        raw_line: Original log line for debugging
    """

    location_id: str
    depth: float
    x_value: float
    y_value: float
    investigation: Optional[str] = None
    raw_line: Optional[str] = None

    def to_tuple(self) -> Tuple[str, float, float, float]:
        """Return hashable tuple for comparison (loc, depth, x, y)."""
        return (self.location_id, self.depth, self.x_value, self.y_value)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, DataPoint):
            return False
        return self.to_tuple() == other.to_tuple()

    def __hash__(self) -> int:
        return hash(self.to_tuple())


@dataclass
class FormationData:
    """
    Holds all data points for a single formation.

    Attributes:
        formation_name: Name of the geological formation
        points: List of data points
        source: Source identifier (MONOLITH or MODULAR)
    """

    formation_name: str
    points: List[DataPoint] = field(default_factory=list)
    source: str = ""


@dataclass
class ComparisonResult:
    """
    Results of comparing monolith vs modular data points.

    Attributes:
        formation_name: Formation being compared
        monolith_count: Number of points in monolith
        modular_count: Number of points in modular
        matched_count: Number of exactly matching points
        only_in_monolith: Points present only in monolith
        only_in_modular: Points present only in modular
        is_perfect_match: True if 100% match (THE GOAL)
    """

    formation_name: str
    monolith_count: int
    modular_count: int
    matched_count: int
    only_in_monolith: List[DataPoint] = field(default_factory=list)
    only_in_modular: List[DataPoint] = field(default_factory=list)

    @property
    def is_perfect_match(self) -> bool:
        """Check if this is a 100% perfect match."""
        return (
            self.monolith_count == self.modular_count
            and self.matched_count == self.monolith_count
            and len(self.only_in_monolith) == 0
            and len(self.only_in_modular) == 0
        )

    @property
    def match_percentage(self) -> float:
        """Calculate match percentage."""
        if self.monolith_count == 0:
            return 100.0 if self.modular_count == 0 else 0.0
        return (self.matched_count / self.monolith_count) * 100


# ═══════════════════════════════════════════════════════════════════════════
# 🔍 POINT EXTRACTION FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════


def extract_points_from_log(
    log_path: str,
    source_pattern: str = "MODULAR|MONOLITH",
    formation_filter: Optional[str] = None,
) -> Dict[str, FormationData]:
    """
    Extract data points from a debug log file.

    This function parses log files generated by the debug logging utilities
    and extracts structured data points for comparison.

    Args:
        log_path: Path to the log file
        source_pattern: Regex pattern to identify source (MODULAR or MONOLITH)
        formation_filter: Optional filter to extract only specific formation

    Returns:
        Dictionary mapping formation names to FormationData objects

    Example:
        >>> points = extract_points_from_log("logs/modular.log", "MODULAR")
        >>> print(len(points["Kimmeridge Clay Formation (Weathered)"].points))
        255
    """
    log_file = Path(log_path)
    if not log_file.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")

    formations: Dict[str, FormationData] = {}
    current_formation: Optional[str] = None
    current_source: str = ""

    # Patterns for parsing log lines
    formation_pattern = re.compile(
        r"\[(MODULAR|MONOLITH)\].*(?:DEBUG|Plot Data Debug).*[:-]\s*(.+?)(?:\s*$|\s*\|)"
    )
    # Pattern for data point lines - handles both [M]/[m] and [MODULAR]/[MONOLITH] formats
    point_pattern = re.compile(
        r"\[(?:M|m|MODULAR|MONOLITH)\]\s*(\S+)\s*\|\s*Depth=([^\s|]+)\s*\|\s*X=([^\s|]+)\s*\|\s*Y=([^\s|]+)(?:\s*\|\s*Inv=(.+))?"
    )

    with open(log_file, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            # Check for formation header
            form_match = formation_pattern.search(line)
            if form_match:
                current_source = form_match.group(1)
                current_formation = form_match.group(2).strip()

                # Apply formation filter if specified
                if (
                    formation_filter
                    and formation_filter.lower() not in current_formation.lower()
                ):
                    current_formation = None
                    continue

                if current_formation and current_formation not in formations:
                    formations[current_formation] = FormationData(
                        formation_name=current_formation, source=current_source
                    )
                continue

            # Check for data point line
            point_match = point_pattern.search(line)
            if point_match and current_formation:
                try:
                    loc_id = point_match.group(1)
                    depth = _parse_numeric(point_match.group(2))
                    x_val = _parse_numeric(point_match.group(3))
                    y_val = _parse_numeric(point_match.group(4))
                    inv = point_match.group(5).strip() if point_match.group(5) else None

                    point = DataPoint(
                        location_id=loc_id,
                        depth=depth,
                        x_value=x_val,
                        y_value=y_val,
                        investigation=inv,
                        raw_line=line.strip(),
                    )
                    formations[current_formation].points.append(point)
                except (ValueError, TypeError) as e:
                    logger.warning(f"Failed to parse line: {line.strip()} - {e}")

    return formations


def extract_points_from_text_file(
    file_path: str,
    pattern: Optional[str] = None,
) -> List[DataPoint]:
    """
    Extract data points from a simple text file with one point per line.

    Useful for files created by PowerShell extraction like:
        [M] BH1 | Depth=5.0 | X=100 | Y=0.5

    Args:
        file_path: Path to text file
        pattern: Optional regex pattern for lines to include

    Returns:
        List of DataPoint objects
    """
    points: List[DataPoint] = []
    point_pattern = re.compile(
        r"\[(?:M|m|MODULAR|MONOLITH)\]\s*(\S+)\s*\|\s*Depth=([^\s|]+)\s*\|\s*X=([^\s|]+)\s*\|\s*Y=([^\s|]+)"
    )

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if pattern and not re.search(pattern, line, re.IGNORECASE):
                continue

            match = point_pattern.search(line)
            if match:
                try:
                    points.append(
                        DataPoint(
                            location_id=match.group(1),
                            depth=_parse_numeric(match.group(2)),
                            x_value=_parse_numeric(match.group(3)),
                            y_value=_parse_numeric(match.group(4)),
                            raw_line=line.strip(),
                        )
                    )
                except (ValueError, TypeError):
                    continue

    return points


def _parse_numeric(value: str) -> float:
    """Parse a numeric value from string, handling N/A and nan."""
    value = value.strip()
    if value.lower() in ("n/a", "nan", "none", ""):
        return float("nan")
    return float(value)


# ═══════════════════════════════════════════════════════════════════════════
# ⚖️ COMPARISON FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════


def compare_point_lists(
    monolith_points: List[DataPoint],
    modular_points: List[DataPoint],
    formation_name: str = "Unknown",
) -> ComparisonResult:
    """
    Compare two lists of data points and identify matches/differences.

    THIS IS THE MAIN EVENT OF DEBUGGING.
    A successful monolith-to-modular conversion requires 100% match.

    Args:
        monolith_points: Points from monolith implementation
        modular_points: Points from modular implementation
        formation_name: Name of formation being compared

    Returns:
        ComparisonResult with match statistics and differences

    Example:
        >>> result = compare_point_lists(mono_points, mod_points, "KC UW")
        >>> print(f"Match: {result.match_percentage}%")
        Match: 100.0%
    """
    # Convert to sets of tuples for comparison
    mono_set = {p.to_tuple() for p in monolith_points}
    mod_set = {p.to_tuple() for p in modular_points}

    # Find matches and differences
    matched = mono_set & mod_set
    only_mono = mono_set - mod_set
    only_mod = mod_set - mono_set

    # Convert back to DataPoint objects for detailed reporting
    mono_lookup = {p.to_tuple(): p for p in monolith_points}
    mod_lookup = {p.to_tuple(): p for p in modular_points}

    return ComparisonResult(
        formation_name=formation_name,
        monolith_count=len(monolith_points),
        modular_count=len(modular_points),
        matched_count=len(matched),
        only_in_monolith=[mono_lookup[t] for t in only_mono],
        only_in_modular=[mod_lookup[t] for t in only_mod],
    )


def compare_formations(
    monolith_data: Dict[str, FormationData],
    modular_data: Dict[str, FormationData],
) -> Dict[str, ComparisonResult]:
    """
    Compare all matching formations between monolith and modular data.

    Args:
        monolith_data: Formations extracted from monolith log
        modular_data: Formations extracted from modular log

    Returns:
        Dictionary mapping formation names to ComparisonResult
    """
    results: Dict[str, ComparisonResult] = {}

    # Find common formations
    all_formations = set(monolith_data.keys()) | set(modular_data.keys())

    for formation in all_formations:
        mono_points = monolith_data.get(formation, FormationData(formation)).points
        mod_points = modular_data.get(formation, FormationData(formation)).points

        results[formation] = compare_point_lists(mono_points, mod_points, formation)

    return results


# ═══════════════════════════════════════════════════════════════════════════
# 📝 REPORTING FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════


def print_comparison_report(result: ComparisonResult) -> None:
    """
    Print a detailed comparison report for a single formation.

    Args:
        result: ComparisonResult to report
    """
    print("\n" + "═" * 80)
    print(f"POINT-TO-POINT COMPARISON: {result.formation_name}")
    print("═" * 80)

    # Summary stats
    print(f"\n📊 Point Counts:")
    print(f"   Monolith: {result.monolith_count}")
    print(f"   Modular:  {result.modular_count}")
    print(f"   Matched:  {result.matched_count}")

    # Match percentage (THE MAIN EVENT)
    if result.is_perfect_match:
        print(
            f"\n✅ PERFECT MATCH: {result.match_percentage:.1f}% ({result.matched_count}/{result.monolith_count})"
        )
    else:
        print(
            f"\n❌ MISMATCH: {result.match_percentage:.1f}% ({result.matched_count}/{result.monolith_count})"
        )

        if result.only_in_monolith:
            print(f"\n   Points ONLY in Monolith ({len(result.only_in_monolith)}):")
            for p in result.only_in_monolith[:10]:  # Show first 10
                print(
                    f"      {p.location_id} | Depth={p.depth} | X={p.x_value} | Y={p.y_value}"
                )
            if len(result.only_in_monolith) > 10:
                print(f"      ... and {len(result.only_in_monolith) - 10} more")

        if result.only_in_modular:
            print(f"\n   Points ONLY in Modular ({len(result.only_in_modular)}):")
            for p in result.only_in_modular[:10]:  # Show first 10
                print(
                    f"      {p.location_id} | Depth={p.depth} | X={p.x_value} | Y={p.y_value}"
                )
            if len(result.only_in_modular) > 10:
                print(f"      ... and {len(result.only_in_modular) - 10} more")

    print("\n" + "═" * 80)


def print_full_comparison_summary(results: Dict[str, ComparisonResult]) -> None:
    """
    Print summary report for all formations.

    Args:
        results: Dictionary of ComparisonResults by formation
    """
    print("\n" + "═" * 80)
    print("FULL COMPARISON SUMMARY - POINT-TO-POINT COORDINATE CHECK")
    print("═" * 80)

    perfect_matches = []
    mismatches = []

    for formation, result in results.items():
        if result.is_perfect_match:
            perfect_matches.append(formation)
        else:
            mismatches.append((formation, result))

    # Summary counts
    total = len(results)
    print(f"\n📊 Overall: {len(perfect_matches)}/{total} formations match perfectly")

    # Perfect matches
    if perfect_matches:
        print(f"\n✅ Perfect Matches ({len(perfect_matches)}):")
        for f in perfect_matches:
            r = results[f]
            print(f"   - {f}: {r.matched_count}/{r.monolith_count} points")

    # Mismatches (need attention)
    if mismatches:
        print(f"\n❌ Mismatches ({len(mismatches)}):")
        for f, r in mismatches:
            print(
                f"   - {f}: {r.match_percentage:.1f}% ({r.matched_count}/{r.monolith_count})"
            )
            if r.only_in_monolith:
                print(f"     Missing from modular: {len(r.only_in_monolith)} points")
            if r.only_in_modular:
                print(f"     Extra in modular: {len(r.only_in_modular)} points")

    print("\n" + "═" * 80)

    # Final verdict
    if not mismatches:
        print("🎉 ALL FORMATIONS MATCH - CONVERSION SUCCESSFUL!")
    else:
        print("⚠️  CONVERSION NEEDS REVIEW - SEE MISMATCHES ABOVE")

    print("═" * 80 + "\n")


# ═══════════════════════════════════════════════════════════════════════════
# 🚀 HIGH-LEVEL WORKFLOW FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════


def run_full_comparison(
    monolith_log_path: str,
    modular_log_path: str,
    formation_filter: Optional[str] = None,
    verbose: bool = True,
) -> Dict[str, ComparisonResult]:
    """
    Run a complete point-to-point comparison between monolith and modular logs.

    This is the recommended entry point for comparing implementations.

    Args:
        monolith_log_path: Path to monolith debug log
        modular_log_path: Path to modular debug log
        formation_filter: Optional filter for specific formation
        verbose: If True, print detailed reports

    Returns:
        Dictionary of ComparisonResults by formation

    Example:
        >>> results = run_full_comparison(
        ...     "logs/monolith_mv.log",
        ...     "logs/modular_mv.log",
        ...     formation_filter="Kimmeridge"
        ... )
        >>> all_match = all(r.is_perfect_match for r in results.values())
    """
    logger.info(f"🔍 Starting point-to-point comparison...")
    logger.info(f"   Monolith: {monolith_log_path}")
    logger.info(f"   Modular:  {modular_log_path}")

    # Extract points from both logs
    monolith_data = extract_points_from_log(
        monolith_log_path, "MONOLITH", formation_filter
    )
    modular_data = extract_points_from_log(
        modular_log_path, "MODULAR", formation_filter
    )

    logger.info(f"   Found {len(monolith_data)} formations in monolith")
    logger.info(f"   Found {len(modular_data)} formations in modular")

    # Compare all formations
    results = compare_formations(monolith_data, modular_data)

    # Print reports if verbose
    if verbose:
        print_full_comparison_summary(results)

    return results


def quick_file_compare(
    monolith_points_file: str,
    modular_points_file: str,
    formation_name: str = "Comparison",
) -> ComparisonResult:
    r"""
    Quick comparison of two extracted points files.

    Useful for comparing files created by PowerShell extraction:
        Get-Content log.txt | Select-String -Pattern "\[M\]" > points.txt

    Args:
        monolith_points_file: Path to monolith points text file
        modular_points_file: Path to modular points text file
        formation_name: Name to use in report

    Returns:
        ComparisonResult

    Example:
        >>> result = quick_file_compare(
        ...     "logs/monolith_points.txt",
        ...     "logs/modular_points.txt",
        ...     "KC UW"
        ... )
        >>> print(f"Match: {result.is_perfect_match}")
    """
    mono_points = extract_points_from_text_file(monolith_points_file)
    mod_points = extract_points_from_text_file(modular_points_file)

    result = compare_point_lists(mono_points, mod_points, formation_name)
    print_comparison_report(result)

    return result
